#!/bin/bash

#if gpg --yes --batch --passphrase-file ${SCRIPT_DIR}/pass_file --list-packets $1 > /dev/null 2>&1
#then
# echo "file $1 is not encrypted"
# cat
#fi
gpg --yes --batch --passphrase "${TETAPAC_PASSPHRASE}" --symmetric  --cipher-algo AES256

